root = "../../media_storage/"

TRANSCRIPTS_FOLDER = f'{root}transcripts/'
ANGRY_MUSIC_FOLDER = f'{root}songs/angry/'
CUTE_MUSIC_FOLDER = f'{root}songs/cute/'
FUNNY_MUSIC_FOLDER = f'{root}songs/funny/'
MOTIVATIONAL_MUSIC_FOLDER = f'{root}songs/motivational/'
INTRIGUING_MUSIC_FOLDER = f'{root}songs/fascinating/'
CONSPIRACY_MUSIC_FOLDER = f'{root}songs/conspiracy/'
HOPEFUL_MUSIC_FOLDER = f'{root}songs/hopeful/'
SCARY_MUSIC_FOLDER = f'{root}songs/scary/'
SERIOUS_MUSIC_FOLDER = f'{root}songs/serious/'
FULL_POD_FOLDER = f"{root}full_pod_folder/"
POTENTIAL_CLIP_FOLDER = f"{root}potential_clip_folder/"
SHORTENED_CLIPS_FOLDER = f"{root}shortened_clips/"
AUDIO_EXTRACTIONS_FOLDER = f"{root}audio_extractions/"
IMAGE_FOLDER = f"{root}images/"
IMAGE_2_VIDEOS_FOLDER = f"{root}videos_made_from_images/"
OUTPUT_FOLDER = f"{root}OutputVideos/"
ORIGINAL_INPUT_FOLDER = f"{root}potential_clip_folder/"
CHROME_DRIVER_PATH = f"{root}content_generator/chromedriver.exe"
RESIZED_FOLDER = f"{root}resized_original_videos/"
VIDEOS_WITH_OVERLAYED_MEDIA_PATH = f"{root}media_added_videos/"
QUERY_FOLDER = f'{root}queries/'
INPUT_INFO_FILE = f'{root}input_info.csv'
VIDEO_INFO_FOLDER = f"{root}video_info/"
GENERATED_PROMPTS_FOLDER = f"{root}generated_prompts/"
FINISHED_VIDEOS_FOLDER = f"{root}finished_videos/"
WITH_SUBTITLES_FOLDER = f"{root}subtitled_videos/"
PHOTO_AD_FOLDER = f"{root}photo_ads/"
BANNER_FOLDER = f"{root}banner_ads/"
VIDEOS_WITH_BANNER_FOLDER = f"{root}banner_videos/"
BACKGROUNDLESS_VIDEOS_FOLDER = f"{root}background_removed_videos/"
BACKGROUND_IMAGE_FOLDER = f"{root}background_images/"
IMAGE_SOUNDS_FOLDER = f"{root}image_display_sounds/"
DOWNLOADED_VIDEOS_FILE = f"{root}downloaded_videos/videos.csv"
HOOKS_FOLDER = f"{root}hooks/"
CLIP_END_FOLDER = f"{root}clip_ends/"


folders_dict = {
    'TRANSCRIPTS_FOLDER': TRANSCRIPTS_FOLDER,
    'ANGRY_MUSIC_FOLDER': ANGRY_MUSIC_FOLDER,
    'CUTE_MUSIC_FOLDER': CUTE_MUSIC_FOLDER,
    'FUNNY_MUSIC_FOLDER': FUNNY_MUSIC_FOLDER,
    'MOTIVATIONAL_MUSIC_FOLDER': MOTIVATIONAL_MUSIC_FOLDER,
    'INTRIGUING_MUSIC_FOLDER': INTRIGUING_MUSIC_FOLDER,
    'CONSPIRACY_MUSIC_FOLDER': CONSPIRACY_MUSIC_FOLDER,
    'SCARY_MUSIC_FOLDER': SCARY_MUSIC_FOLDER,
    'FULL_POD_FOLDER': FULL_POD_FOLDER,
    'INPUT_FOLDER': POTENTIAL_CLIP_FOLDER,
    'AUDIO_EXTRACTIONS_FOLDER': AUDIO_EXTRACTIONS_FOLDER,
    'IMAGE_FOLDER': IMAGE_FOLDER,
    'IMAGE_2_VIDEOS_FOLDER': IMAGE_2_VIDEOS_FOLDER,
    'OUTPUT_FOLDER': OUTPUT_FOLDER,
    'ORIGINAL_INPUT_FOLDER': ORIGINAL_INPUT_FOLDER,
    'CHROME_DRIVER_PATH': CHROME_DRIVER_PATH,
    'RESIZED_FOLDER': RESIZED_FOLDER,
    'VIDEOS_WITH_OVERLAYED_MEDIA_PATH': VIDEOS_WITH_OVERLAYED_MEDIA_PATH,
    'QUERY_FOLDER': QUERY_FOLDER,
    'INPUT_INFO_FILE': INPUT_INFO_FILE,
    'VIDEO_INFO_FOLDER': VIDEO_INFO_FOLDER,
    'GENERATED_PROMPTS_FOLDER': GENERATED_PROMPTS_FOLDER,
    'FINISHED_VIDEOS_FOLDER': FINISHED_VIDEOS_FOLDER,
    'WITH_SUBTITLES_FOLDER': WITH_SUBTITLES_FOLDER,
    'PHOTO_AD_FOLDER': PHOTO_AD_FOLDER,
    'BANNER_FOLDER': BANNER_FOLDER,
    'VIDEOS_WITH_BANNER_FOLDER': VIDEOS_WITH_BANNER_FOLDER,
    'BACKGROUNDLESS_VIDEOS_FOLDER': BACKGROUNDLESS_VIDEOS_FOLDER,
    'BACKGROUND_IMAGE_FOLDER': BACKGROUND_IMAGE_FOLDER,
    'IMAGE_SOUNDS_FOLDER': IMAGE_SOUNDS_FOLDER,
    'DOWNLOADED_VIDEOS_FILE': DOWNLOADED_VIDEOS_FILE,
    'HOOKS_FOLDER': HOOKS_FOLDER
}


MUSIC_CATEGORY_PATH_DICT = {
    'funny': FUNNY_MUSIC_FOLDER,
    'cute': CUTE_MUSIC_FOLDER,
    'motivational': MOTIVATIONAL_MUSIC_FOLDER,
    'fascinating': INTRIGUING_MUSIC_FOLDER,
    'angry': ANGRY_MUSIC_FOLDER,
    'conspiracy': CONSPIRACY_MUSIC_FOLDER,
    'scary': SCARY_MUSIC_FOLDER,
    'hopeful': HOPEFUL_MUSIC_FOLDER,
    'serious': SERIOUS_MUSIC_FOLDER
}