VERTICAL_VIDEO_HEIGHT = 1920
VERTICAL_VIDEO_WIDTH = 1080
HORIZONTAL_VIDEO_HEIGHT = 1080
HORIZONTAL_VIDEO_WIDTH = 1920
bottom_vert = "bottom_vert"
top_vert = "top_vert"
top_right_hor = "top_right_hor"
top_left_hor = "top_left_hor"
bottom_right_hor = "bottom_right_hor"
bottom_left_hor = "bottom_left_hor"
center = "center"

themes = {
    "curious_primates":
    {
        "HEAD_TRACKING_ENABLED" : True,
        "SECONDS_PER_PHOTO" : 4,
        "PERECENT_OF_IMAGES_TO_BE_FULLSCREEN" : 0,
        "MAXIMUM_PAUSE_LENGTH" : 0.35,
        "TIME_BETWEEN_IMAGES" : 0,
        "Y_PERCENT_HEIGHT_OF_SUBTITLE" : 55,
        "SUBTITLE_DURATION" : 1,
        "DURATION_OF_FULL_SCREEN_IMAGES" : 3.5,
        "FONT" : 'Tahoma Bold.ttf',
        "FONT_OUTLINE_COLOR" : (0, 0, 0),
        "FONT_OUTLINE_WIDTH" : 7,
        "FONT_SIZE" : 90,
        "NUMBER_OF_CHARACTERS_PER_LINE" : 17,
        "FONT_COLOR" : (255, 255, 255), # white
        "WANTS_IMAGES" : True,
        "IMAGE_BORDER_COLOR(S)" : [ (124,252,0), # green
                                    (0,245,255), # cyan
                                    (255,255,0), # yellow
                                    (255,48,48), # red
                                    (0,191,255)], # blue
        "MUSIC_CATEGORY_OPTIONS" : ["fascinating", "mystery", "motivational", "funny"],
        "WANTS_ADS" : False,
        "CENSOR_PROFANITY" : False,
        "ALL_CAPS": False,
        "PUNCTUATION": True,
        "OVERLAY_ZONE_TOP_LEFT": [0, 1300],
        "OVERLAY_ZONE_WIDTH": 1080,
        "OVERLAY_ZONE_HEIGHT": 400,
        "BACKGROUND_MUSIC_VOLUME": 0.8,
        "WANTS_SOUND_EFFECTS": True,
        "ZOOM_SPEED": 'fast',
        "WANTS_ROYALTY_FREE_IMAGES": False,
        "WATERMARK": 'curious_primates.png',
        "WATERMARK_LOCATION": top_vert,
        "INTRO_FILE": None,
        "AUDIO_ONLY_BACKGROUND_MEDIA": ["clouds_1.mp4", "clouds_2.mp4", "clouds_3.mp4"],
    },
    "one_percent_minds":
    {
        "HEAD_TRACKING_ENABLED" : True,
        "SECONDS_PER_PHOTO" : 4,
        "PERECENT_OF_IMAGES_TO_BE_FULLSCREEN" : 0,
        "MAXIMUM_PAUSE_LENGTH" : 0.4,
        "TIME_BETWEEN_IMAGES" : 0,
        "Y_PERCENT_HEIGHT_OF_SUBTITLE" : 60,
        "SUBTITLE_DURATION" : 1,
        "DURATION_OF_FULL_SCREEN_IMAGES" : 3.5,
        "FONT" : 'Tahoma Bold.ttf',
        "FONT_OUTLINE_COLOR" : (0, 0, 0),
        "FONT_OUTLINE_WIDTH" : 6,
        "FONT_SIZE" : 80,
        "NUMBER_OF_CHARACTERS_PER_LINE" : 20,
        "FONT_COLOR" : (255,193,37), # gold
        "WANTS_IMAGES" : True,
        "IMAGE_BORDER_COLOR(S)" : [(0, 0, 0), (136, 8, 8)], # black, red
        "MUSIC_CATEGORY_OPTIONS" : ["motivational", "scary", "hopeful"],
        "WANTS_ADS" : True,
        "BANNER": "zero.mp4",
        "BANNER_START_TIMES": [10, 45],
        "CENSOR_PROFANITY": False,
        "ALL_CAPS": False,
        "PUNCTUATION": True,
        "OVERLAY_ZONE_TOP_LEFT": [0, 1300],
        "OVERLAY_ZONE_WIDTH": 1080,
        "OVERLAY_ZONE_HEIGHT": 400,
        "BACKGROUND_MUSIC_VOLUME": 0.8,
        "WANTS_SOUND_EFFECTS": True,
        "ZOOM_SPEED": 'slow',
        "WANTS_ROYALTY_FREE_IMAGES": False,
        "WATERMARK": 'one_percent_minds.png',
        "WATERMARK_LOCATION": top_vert,
        "INTRO_FILE": None,
        "AUDIO_ONLY_BACKGROUND_MEDIA": ["clouds_1.mp4", "clouds_2.mp4", "clouds_3.mp4"],
    },
    "girly":
    {
        "HEAD_TRACKING_ENABLED" : True,
        "SECONDS_PER_PHOTO" : 6,
        "PERECENT_OF_IMAGES_TO_BE_FULLSCREEN" : 0.3,
        "MAXIMUM_PAUSE_LENGTH" : 0.5,
        "TIME_BETWEEN_IMAGES" : 1.5,
        "Y_PERCENT_HEIGHT_OF_SUBTITLE" : 60,
        "SUBTITLE_DURATION" : 1,
        "DURATION_OF_FULL_SCREEN_IMAGES" : 3,
        "FONT" : 'Comic Sans MS Bold.ttf',
        "FONT_OUTLINE_COLOR" : (255,105,180), # hot pink
        "FONT_SIZE" : 80,
        "NUMBER_OF_CHARACTERS_PER_LINE" : 20,
        "FONT_COLOR" : (255,255,255), # white
        "WANTS_IMAGES" : True,
        "IMAGE_BORDER_COLOR(S)" : [(255,255,255)],
        "MUSIC_CATEGORY_OPTIONS" : ["cute", "funny"],
        "WANTS_ADS" : False,
        "BANNER": None,
        "BANNER_START_TIMES": [],
        "BACKGROUND_MUSIC_VOLUME": 0.8,
        "WANTS_SOUND_EFFECTS": True,
        "ZOOM_SPEED": 'fast',
        "WANTS_ROYALTY_FREE_IMAGES": False,
        "WATERMARK": None,
        "WATERMARK_LOCATION": center,
        "INTRO_FILE": None,
    },
    "political_1":
    {
        "HEAD_TRACKING_ENABLED" : True,
        "SECONDS_PER_PHOTO" : 6,
        "PERECENT_OF_IMAGES_TO_BE_FULLSCREEN" : 0.3,
        "MAXIMUM_PAUSE_LENGTH" : 0.5,
        "TIME_BETWEEN_IMAGES" : 1.5,
        "Y_PERCENT_HEIGHT_OF_SUBTITLE" : 60,
        "SUBTITLE_DURATION" : 1,
        "DURATION_OF_FULL_SCREEN_IMAGES" : 3,
        "FONT" :  "Times New Roman Bold Italic.ttf",
        "FONT_OUTLINE_COLOR" : (0, 0, 0),
        "FONT_OUTLINE_WIDTH" : 8,
        "FONT_SIZE" : 90,
        "NUMBER_OF_CHARACTERS_PER_LINE" : 20,
        "FONT_COLOR" : (255,255,255), # white
        "WANTS_IMAGES" : True,
        "IMAGE_BORDER_COLOR(S)" : [(0, 0, 0)], # black
        "MUSIC_CATEGORY_OPTIONS" : ["motivational", "scary", "fascinating", "funny", "hopeful"],
        "WANTS_ADS" : False,
        "BANNER": "zero.mp4",
        "BANNER_START_TIMES": [10],
        "CENSOR_PROFANITY": True,
        "ALL_CAPS": True,
        "PUNCTUATION": False,
        "OVERLAY_ZONE_TOP_LEFT": [0, 1344],
        "OVERLAY_ZONE_WIDTH": 1080,
        "OVERLAY_ZONE_HEIGHT": 520,
        "BACKGROUND_MUSIC_VOLUME": 0.75,
        "WANTS_SOUND_EFFECTS": True,
        "ZOOM_SPEED": 'fast',
        "WANTS_ROYALTY_FREE_IMAGES": False,
        "WATERMARK": None,
        "WATERMARK_LOCATION": center,
        "INTRO_FILE": None,
    },
    "political_2":
    {
        "HEAD_TRACKING_ENABLED" : True,
        "SECONDS_PER_PHOTO" : 6,
        "PERECENT_OF_IMAGES_TO_BE_FULLSCREEN" : 0.3,
        "MAXIMUM_PAUSE_LENGTH" : 0.5,
        "TIME_BETWEEN_IMAGES" : 1.5,
        "Y_PERCENT_HEIGHT_OF_SUBTITLE" : 60,
        "SUBTITLE_DURATION" : 1,
        "DURATION_OF_FULL_SCREEN_IMAGES" : 3,
        "FONT" :  "Tahoma Bold.ttf",
        "FONT_OUTLINE_COLOR" : (0, 0, 0),
        "FONT_OUTLINE_WIDTH" : 7,
        "FONT_SIZE" : 90,
        "NUMBER_OF_CHARACTERS_PER_LINE" : 17,
        "FONT_COLOR" : (255,255,255), # white
        "WANTS_IMAGES" : True,
        "IMAGE_BORDER_COLOR(S)" : [(0, 0, 0)], # black
        "MUSIC_CATEGORY_OPTIONS" : ["motivational", "scary", "fascinating", "funny", "hopeful"],
        "WANTS_ADS" : False,
        "BANNER": "zero.mp4",
        "BANNER_START_TIMES": [10],
        "CENSOR_PROFANITY": True,
        "ALL_CAPS": True,
        "PUNCTUATION": False,
        "OVERLAY_ZONE_TOP_LEFT": [0, 1344],
        "OVERLAY_ZONE_WIDTH": 1080,
        "OVERLAY_ZONE_HEIGHT": 520,
        "BACKGROUND_MUSIC_VOLUME": 0.75,
        "WANTS_SOUND_EFFECTS": True,
        "ZOOM_SPEED": 'fast',
        "WANTS_ROYALTY_FREE_IMAGES": False,
        "WATERMARK": None,
        "WATERMARK_LOCATION": center,
        "INTRO_FILE": None,
    },
        "political_3":
    {
        "HEAD_TRACKING_ENABLED" : True,
        "SECONDS_PER_PHOTO" : 6,
        "PERECENT_OF_IMAGES_TO_BE_FULLSCREEN" : 0,
        "MAXIMUM_PAUSE_LENGTH" : 0.5,
        "TIME_BETWEEN_IMAGES" : 1.5,
        "Y_PERCENT_HEIGHT_OF_SUBTITLE" : 60,
        "SUBTITLE_DURATION" : 1,
        "DURATION_OF_FULL_SCREEN_IMAGES" : 3,
        "FONT" :  "Tahoma Bold.ttf",
        "FONT_OUTLINE_COLOR" : (0, 0, 0),
        "FONT_OUTLINE_WIDTH" : 6,
        "FONT_SIZE" : 80,
        "NUMBER_OF_CHARACTERS_PER_LINE" : 20,
        "FONT_COLOR" : (255,255,255),
        "WANTS_IMAGES" : True,
        "IMAGE_BORDER_COLOR(S)" : [(0, 0, 0)], # black
        "MUSIC_CATEGORY_OPTIONS" : ["motivational",
                                    "scary",
                                    "fascinating",
                                    "funny",
                                    "hopeful",
                                    "serious"],
        "WANTS_ADS" : False,
        "BANNER": "zero.mp4",
        "BANNER_START_TIMES": [10],
        "CENSOR_PROFANITY": True,
        "ALL_CAPS": False,
        "PUNCTUATION": True,
        "OVERLAY_ZONE_TOP_LEFT": [0, 1500],
        "OVERLAY_ZONE_WIDTH": 1080,
        "OVERLAY_ZONE_HEIGHT": 420,
        "BACKGROUND_MUSIC_VOLUME": 0.75,
        "WANTS_SOUND_EFFECTS": True,
        "ZOOM_SPEED": 'fast',
        "WANTS_ROYALTY_FREE_IMAGES": False,
        "WATERMARK": None,
        "WATERMARK_LOCATION": center,
        "INTRO_FILE": None,
    },
        "jar":
    {
        "HEAD_TRACKING_ENABLED" : True,
        "SECONDS_PER_PHOTO" : 5,
        "PERECENT_OF_IMAGES_TO_BE_FULLSCREEN" : 0,
        "MAXIMUM_PAUSE_LENGTH" : 0.5,
        "TIME_BETWEEN_IMAGES" : 0,
        "Y_PERCENT_HEIGHT_OF_SUBTITLE" : 85,
        "SUBTITLE_DURATION" : 1,
        "DURATION_OF_FULL_SCREEN_IMAGES" : 5,
        "FONT" :  "Tahoma Bold.ttf",
        "FONT_OUTLINE_COLOR" : (0, 0, 0),
        "FONT_OUTLINE_WIDTH" : 6,
        "FONT_SIZE" : 80,
        "NUMBER_OF_CHARACTERS_PER_LINE" : 30,
        "FONT_COLOR" : (255,255,255),
        "WANTS_IMAGES" : True,
        "IMAGE_BORDER_COLOR(S)" : [(0, 0, 0)], # black
        "MUSIC_CATEGORY_OPTIONS" : ["motivational", "scary", "fascinating", "funny", "hopeful", "serious"],
        "WANTS_ADS" : False,
        "BANNER": "zero.mp4",
        "BANNER_START_TIMES": [10],
        "CENSOR_PROFANITY": True,
        "ALL_CAPS": False,
        "PUNCTUATION": True,
        "OVERLAY_ZONE_TOP_LEFT": [0, 0],
        "OVERLAY_ZONE_WIDTH": 1920,
        "OVERLAY_ZONE_HEIGHT": 1080,
        "BACKGROUND_MUSIC_VOLUME": 0.75,
        "WANTS_SOUND_EFFECTS": False,
        "AUDIO_ONLY_BACKGROUND_COLOR": (255, 255, 255),
        "AUDIO_ONLY_BACKGROUND_MEDIA": ["clouds_1.mp4", "clouds_2.mp4", "clouds_3.mp4"],
        "ZOOM_SPEED": 'slow',
        "WANTS_ROYALTY_FREE_IMAGES": True,
        "WATERMARK": 'jar.png',
        "WATERMARK_LOCATION": top_left_hor,
        "INTRO_FILE": 'jar.mp4',
    },
    "horizontal":
    {
        "HEAD_TRACKING_ENABLED" : True,
        "SECONDS_PER_PHOTO" : 5,
        "PERECENT_OF_IMAGES_TO_BE_FULLSCREEN" : 0,
        "MAXIMUM_PAUSE_LENGTH" : 0.5,
        "TIME_BETWEEN_IMAGES" : 0,
        "Y_PERCENT_HEIGHT_OF_SUBTITLE" : 85,
        "SUBTITLE_DURATION" : 1,
        "DURATION_OF_FULL_SCREEN_IMAGES" : 5,
        "FONT" :  "Tahoma Bold.ttf",
        "FONT_OUTLINE_COLOR" : (0, 0, 0),
        "FONT_OUTLINE_WIDTH" : 6,
        "FONT_SIZE" : 80,
        "NUMBER_OF_CHARACTERS_PER_LINE" : 30,
        "FONT_COLOR" : (255,255,255),
        "WANTS_IMAGES" : True,
        "IMAGE_BORDER_COLOR(S)" : [(0, 0, 0)], # black
        "MUSIC_CATEGORY_OPTIONS" : ["motivational", "scary", "fascinating", "funny", "hopeful", "serious"],
        "WANTS_ADS" : False,
        "BANNER": "zero.mp4",
        "BANNER_START_TIMES": [10],
        "CENSOR_PROFANITY": True,
        "ALL_CAPS": False,
        "PUNCTUATION": True,
        "OVERLAY_ZONE_TOP_LEFT": [0, 0],
        "OVERLAY_ZONE_WIDTH": 1920,
        "OVERLAY_ZONE_HEIGHT": 1080,
        "BACKGROUND_MUSIC_VOLUME": 0.75,
        "WANTS_SOUND_EFFECTS": False,
        "AUDIO_ONLY_BACKGROUND_COLOR": (255, 255, 255),
        "AUDIO_ONLY_BACKGROUND_MEDIA": "trippy_purple.mp4",
        "ZOOM_SPEED": 'slow',
        "WANTS_ROYALTY_FREE_IMAGES": True,
        "WATERMARK": None,
        "WATERMARK_LOCATION": top_right_hor,
        "INTRO_FILE": None,
    },
    "Kinvestor":
    {
        "HEAD_TRACKING_ENABLED" : True,
        "SECONDS_PER_PHOTO" : 4,
        "PERECENT_OF_IMAGES_TO_BE_FULLSCREEN" : 0,
        "MAXIMUM_PAUSE_LENGTH" : 0.35,
        "TIME_BETWEEN_IMAGES" : 0,
        "Y_PERCENT_HEIGHT_OF_SUBTITLE" : 85,
        "SUBTITLE_DURATION" : 1,
        "DURATION_OF_FULL_SCREEN_IMAGES" : 3.5,
        "FONT" : 'Tahoma Bold.ttf',
        "FONT_OUTLINE_COLOR" : (0, 0, 0),
        "FONT_OUTLINE_WIDTH" : 7,
        "FONT_SIZE" : 90,
        "NUMBER_OF_CHARACTERS_PER_LINE" : 17,
        "FONT_COLOR" : (255, 255, 255), # white
        "WANTS_IMAGES" : False,
        "IMAGE_BORDER_COLOR(S)" : [(0, 0, 0)],
        "MUSIC_CATEGORY_OPTIONS" : ["fascinating", "motivational", "funny", "mystery"],
        "WANTS_ADS" : False,
        "CENSOR_PROFANITY" : False,
        "ALL_CAPS": False,
        "PUNCTUATION": True,
        "OVERLAY_ZONE_TOP_LEFT": [0, 1300],
        "OVERLAY_ZONE_WIDTH": 1080,
        "OVERLAY_ZONE_HEIGHT": 400,
        "BACKGROUND_MUSIC_VOLUME": 0.8,
        "WANTS_SOUND_EFFECTS": True,
        "ZOOM_SPEED": 'fast',
        "WANTS_ROYALTY_FREE_IMAGES": False,
        "WATERMARK": None,
        "WATERMARK_LOCATION": center,
        "INTRO_FILE": None,
    },
    "curious_primates_long_form":
    {
        "HEAD_TRACKING_ENABLED" : True,
        "SECONDS_PER_PHOTO" : 4,
        "PERECENT_OF_IMAGES_TO_BE_FULLSCREEN" : 0,
        "MAXIMUM_PAUSE_LENGTH" : 0.35,
        "TIME_BETWEEN_IMAGES" : 0,
        "Y_PERCENT_HEIGHT_OF_SUBTITLE" : 85,
        "SUBTITLE_DURATION" : 1,
        "DURATION_OF_FULL_SCREEN_IMAGES" : 3.5,
        "FONT" : 'Tahoma Bold.ttf',
        "FONT_OUTLINE_COLOR" : (0, 0, 0),
        "FONT_OUTLINE_WIDTH" : 7,
        "FONT_SIZE" : 90,
        "NUMBER_OF_CHARACTERS_PER_LINE" : 17,
        "FONT_COLOR" : (255, 255, 255), # white
        "WANTS_IMAGES" : True,
        "IMAGE_BORDER_COLOR(S)" : [ (124,252,0), # green
                                    (0,245,255), # cyan
                                    (255,255,0), # yellow
                                    (255,48,48), # red
                                    (0,191,255)], # blue
        "MUSIC_CATEGORY_OPTIONS" : ["fascinating", "mystery", "motivational", "funny"],
        "WANTS_ADS" : False,
        "CENSOR_PROFANITY" : False,
        "ALL_CAPS": False,
        "PUNCTUATION": True,
        "OVERLAY_ZONE_TOP_LEFT": [0, 0],
        "OVERLAY_ZONE_WIDTH": 1920,
        "OVERLAY_ZONE_HEIGHT": 1080,
        "BACKGROUND_MUSIC_VOLUME": 0.8,
        "WANTS_SOUND_EFFECTS": False,
        "ZOOM_SPEED": 'fast',
        "WANTS_ROYALTY_FREE_IMAGES": False,
        "WATERMARK": 'curious_primates.png',
        "WATERMARK_LOCATION": top_left_hor,
        "INTRO_FILE": None,
        "AUDIO_ONLY_BACKGROUND_COLOR": (255, 255, 255),
        "AUDIO_ONLY_BACKGROUND_MEDIA": ["clouds_1.mp4", "clouds_2.mp4", "clouds_3.mp4"],
    },
}



